import Head from 'next/head';
import Header from '../components/Header';
import { useSession, getSession } from 'next-auth/client';
import Login from '../components/Login';
import Sidebar from '../components/Sidebar';
import Feed from '../components/Feed';
import Widgets from '../components/Widgets';
import { db } from '../firebase';

export default function Home({ session, posts }) {
  if (!session) return <Login />;
  return (
    <div className='h-screen bg-gray-100 overflow-hidden'>
      <Head>
        <title>Facebook Clone</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {/* header */}
      <Header />

      <main className='flex '>
        {/* sidebar */}
        <Sidebar />

        {/* feed */}
        <Feed posts={posts} />

        {/* widgets */}
        <Widgets />
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  // To get the user
  const session = await getSession(context);

  // prefetching the posts from the server for fast rendering
  const posts = await db.collection('posts').orderBy('timestamp', 'desc').get();
  const docs = posts.docs.map((post) => ({
    id: post.id,
    ...post.data(),
    timestamp: null,
  }));

  return {
    props: {
      session,
      posts: docs,
    },
  };
}
